import bcrypt from "bcryptjs";
import { prisma } from "../src/lib/db";
import type { SkillLevel } from "@prisma/client";

// Real content from AGENTS.md Section 8. Open Question 2 (seed-script
// approach): the single admin account's password is hashed from
// ADMIN_EMAIL/ADMIN_PASSWORD in .env — never hardcoded, never generated by
// this script itself.
async function seedAdminUser() {
  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  if (!email || !password) {
    throw new Error(
      "ADMIN_EMAIL and ADMIN_PASSWORD must be set in .env before seeding (Open Question 2)."
    );
  }

  const hashedPassword = await bcrypt.hash(password, 12);
  await prisma.user.upsert({
    where: { email },
    create: { email, hashedPassword },
    update: { hashedPassword },
  });
}

// Every skill in AGENTS.md Section 8, exactly as listed — including Context
// Engineering appearing under both Product Engineering and AI and
// Automation, since the source lists it in both categories deliberately
// rather than as a duplicate to dedupe.
const SKILLS: { name: string; category: string; level: SkillLevel }[] = [
  { name: "Next.js", category: "Product Engineering", level: "ADVANCED" },
  { name: "TypeScript", category: "Product Engineering", level: "PROFICIENT" },
  { name: "Prisma", category: "Product Engineering", level: "PROFICIENT" },
  { name: "PostgreSQL", category: "Product Engineering", level: "PROFICIENT" },
  { name: "Supabase", category: "Product Engineering", level: "PROFICIENT" },
  { name: "Vercel deployment", category: "Product Engineering", level: "ADVANCED" },
  { name: "Context Engineering", category: "Product Engineering", level: "ADVANCED" },

  { name: "Product Requirements Documentation", category: "Product Management", level: "PROFICIENT" },
  { name: "User Research & Interviews", category: "Product Management", level: "PROFICIENT" },
  { name: "Roadmapping & Prioritization", category: "Product Management", level: "LEARNING" },
  { name: "Stakeholder Communication", category: "Product Management", level: "LEARNING" },
  { name: "Product Strategy", category: "Product Management", level: "LEARNING" },

  { name: "Figma", category: "Design", level: "PROFICIENT" },
  { name: "Design systems", category: "Design", level: "PROFICIENT" },
  { name: "Typography and colour theory", category: "Design", level: "PROFICIENT" },

  { name: "OpenAI API", category: "AI and Automation", level: "PROFICIENT" },
  { name: "Prompt Engineering", category: "AI and Automation", level: "ADVANCED" },
  { name: "Context Engineering", category: "AI and Automation", level: "ADVANCED" },
  { name: "AI-assisted development", category: "AI and Automation", level: "ADVANCED" },

  { name: "Technical Writing", category: "Writing and Documentation", level: "ADVANCED" },
  { name: "PRD Writing", category: "Writing and Documentation", level: "ADVANCED" },
  { name: "Medium articles", category: "Writing and Documentation", level: "PROFICIENT" },
];

async function seedSkills() {
  for (const skill of SKILLS) {
    const existing = await prisma.skill.findFirst({
      where: { name: skill.name, category: skill.category },
    });
    if (existing) {
      await prisma.skill.update({ where: { id: existing.id }, data: skill });
    } else {
      await prisma.skill.create({ data: skill });
    }
  }
}

type SeedProject = {
  title: string;
  description: string;
  techStack: string[];
  category: string[];
  liveUrl: string | null;
  githubUrl: string | null;
  screenshots: string[];
  featured: boolean;
  published: boolean;
  completedAt: Date | null;
};

// Real data given directly, Checkpoint 5/6. Async Standup App is
// intentionally NOT included yet — its tech stack wasn't given (unlike the
// four Provly slices below, which each listed theirs) and techStack is a
// required field; fabricating one for a real, named project isn't a
// defensible guess. SpendTrack Expense Tracker is dropped per instruction.
const PROJECTS: SeedProject[] = [
  {
    title: "Provly",
    description:
      "AI field reporting tool for African tradespeople, validated through direct customer interviews. MVP build starting next week.",
    // Not explicitly given for the umbrella product itself — inferred as
    // the stack common to all four slices below, since they're literally
    // its constituent parts. Flagged as an inference, not given verbatim
    // like the slices' own stacks.
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    category: ["AI Tool", "Startup"],
    liveUrl: "https://useprovly.com",
    githubUrl: null,
    screenshots: [],
    featured: true,
    published: true,
    completedAt: null, // in progress
  },
  {
    title: "Auth Slice",
    description:
      "Standalone authentication system with bcrypt hashing, session management, and rate limiting. Found and fixed a real bug where the signup flow incorrectly treated verified accounts as incomplete.",
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    category: ["Web App"],
    liveUrl: null,
    githubUrl: "https://github.com/Khenny-Zenesis/provly-ai.auth",
    screenshots: [],
    featured: false,
    published: true,
    completedAt: new Date("2026-09-07"),
  },
  {
    title: "Billing Slice",
    description:
      "Subscription and payment system on Flutterwave, with proration, webhooks, and idempotency. Caught and fixed a 100x overcharge bug from a currency-unit mismatch before it reached a real transaction.",
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Flutterwave"],
    category: ["Web App"],
    liveUrl: null,
    githubUrl: "https://github.com/Khenny-Zenesis/Provly.ai2.billing",
    screenshots: [],
    featured: false,
    published: true,
    completedAt: new Date("2026-09-08"),
  },
  {
    title: "AI Integration Slice",
    description:
      "Turns job-site photos and voice notes into structured reports with automatic hazard flagging, using OpenAI Whisper and GPT-4o-mini through background jobs.",
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "OpenAI API", "Vercel Blob"],
    category: ["AI Tool"],
    liveUrl: null,
    githubUrl: "https://github.com/Khenny-Zenesis/provly.ai.integration",
    screenshots: [],
    featured: false,
    published: true,
    completedAt: new Date("2026-09-09"),
  },
  {
    title: "Records & Access Slice",
    description:
      "Records system enforcing strict per-user data isolation, audit logging, and query-level ownership scoping.",
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    category: ["Web App"],
    liveUrl: null,
    githubUrl: "https://github.com/Khenny-Zenesis/provly.record-access",
    screenshots: [],
    featured: false,
    published: true,
    completedAt: new Date("2026-09-09"),
  },
  {
    title: "This Portfolio",
    description:
      "AI-powered personal portfolio with chatbot and cover letter generator.",
    // The actual, verifiable stack of this codebase (AGENTS.md Section 2 /
    // package.json) — not an inference, this is literally what it's built
    // with.
    techStack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "NextAuth", "Tailwind CSS", "Vercel Blob"],
    category: ["AI Tool"],
    liveUrl: null,
    githubUrl: null,
    screenshots: [],
    featured: false,
    published: false, // still being built
    completedAt: null,
  },
];

async function seedProjects() {
  for (const project of PROJECTS) {
    const existing = await prisma.project.findFirst({ where: { title: project.title } });
    if (existing) {
      await prisma.project.update({ where: { id: existing.id }, data: project });
    } else {
      await prisma.project.create({ data: project });
    }
  }
}

async function main() {
  await seedAdminUser();
  await seedSkills();
  await seedProjects();
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
